<ul class="diacritrics-keyboard hidden">
    <li class ="diacritics btn btn-sm">á</li>
    <li class ="diacritics btn btn-sm">ã</li>
    <li class ="diacritics btn btn-sm">ā</li>
    <li class ="diacritics btn btn-sm">ǎ</li>
    <li class ="diacritics btn btn-sm">ɔ</li>
    <li class ="diacritics btn btn-sm">ɔ̀</li>
    <li class ="diacritics btn btn-sm">ɔ́</li>
    <li class ="diacritics btn btn-sm">ɔ̄</li>
    <li class ="diacritics btn btn-sm">ɔ̌</li>
    <li class ="diacritics btn btn-sm">ɛ</li>
    <li class ="diacritics btn btn-sm">ɛ̀</li>
    <li class ="diacritics btn btn-sm">ɛ́</li>
    <li class ="diacritics btn btn-sm">ɛ̄</li>
    <li class ="diacritics btn btn-sm">ɛ̌</li>
    <li class ="diacritics btn btn-sm">ò</li>
    <li class ="diacritics btn btn-sm" style="clear: left">ó</li>
    <li class ="diacritics btn btn-sm">ǒ</li>
    <li class ="diacritics btn btn-sm">ō</li>
    <li class ="diacritics btn btn-sm">ć</li>
    <li class ="diacritics btn btn-sm">č</li>
    <li class ="diacritics btn btn-sm">ɖ</li>
    <li class ="diacritics btn btn-sm">ì</li>
    <li class ="diacritics btn btn-sm">í</li>
    <li class ="diacritics btn btn-sm">ǐ</li>
    <li class ="diacritics btn btn-sm">ī</li>
    <li class ="diacritics btn btn-sm">é</li>
    <li class ="diacritics btn btn-sm">è</li>
    <li class ="diacritics btn btn-sm">ě</li>
    <li class ="diacritics btn btn-sm">ē</li>
    <li class ="diacritics btn btn-sm">ŋ</li>
    <li class ="diacritics btn btn-sm wiki-kouman">ɔ</li>
    <li class ="diacritics btn btn-sm wiki-kouman">ὶ</li>
    <li class ="diacritics btn btn-sm wiki-kouman">ί</li>
    <li class ="diacritics btn btn-sm wiki-kouman">ʋ</li>
    <li class ="diacritics btn btn-sm wiki-kouman">ᶓ</li>
    <li class ="diacritics btn btn-sm wiki-kouman">ύ</li>
    <li class ="diacritics btn btn-sm wiki-kouman">ό</li>
    <li class ="diacritics btn btn-sm wiki-kouman">ɩ</li>
    <li class ="diacritics btn btn-sm wiki-kouman">ĺ</li>
    <li class ="diacritics btn btn-sm wiki-kouman">ᵝ</li>
    <li class ="diacritics btn btn-sm wiki-kouman">ä</li>
    <li class ="diacritics btn btn-sm wiki-kouman">ᶴ</li>
    <li class ="diacritics btn btn-sm wiki-kouman">ʃ</li>
    <li class ="diacritics btn btn-sm wiki-kouman">ʋ</li>
    <!-- WYSIWYG -->
    <li class ="functions bold btn btn-sm fa fa-bold"></li>
    <li class ="functions italicize btn btn-sm fa fa-italic"></li>
    <li class ="functions left-shift btn btn-sm">⇧</i></li>
    <li class ="functions capslock btn btn-sm">⇪</li>
    <li class ="close fa fa-times"></li>
</ul>
